include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ─── Error Prevention ─────────────────────────────────────────
    - avoid_print
    - avoid_relative_lib_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_nullable_for_final_variable_declarations
    
    # ─── Style ────────────────────────────────────────────────────
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_unnecessary_containers
    - prefer_is_empty
    - prefer_is_not_empty
    - sort_child_properties_last
    - use_build_context_synchronously
    
    # ─── Documentation ────────────────────────────────────────────
    - slash_for_doc_comments

analyzer:
  errors:
    avoid_print: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
