import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_client/services/lg_service.dart';

/// KML Balloon demo – teaches students how to create rich HTML
/// balloons inside KML placemarks and display them on Liquid Galaxy.
///
/// Provides text fields for title, description, and image URL,
/// generates the balloon KML with embedded HTML, shows a preview,
/// and offers a button to push it to the LG rig.
class BalloonScreen extends StatefulWidget {
  const BalloonScreen({super.key});

  @override
  State<BalloonScreen> createState() => _BalloonScreenState();
}

class _BalloonScreenState extends State<BalloonScreen> {
  final _titleController = TextEditingController(text: 'Lleida');
  final _descriptionController = TextEditingController(
    text: 'A beautiful city in Catalonia, Spain.',
  );
  final _imageUrlController = TextEditingController(
    text: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/'
        'La_Seu_Vella_de_Lleida.jpg/640px-La_Seu_Vella_de_Lleida.jpg',
  );
  final _latController = TextEditingController(text: '41.6176');
  final _lngController = TextEditingController(text: '0.6200');

  bool _isSending = false;
  String? _statusMessage;

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _imageUrlController.dispose();
    _latController.dispose();
    _lngController.dispose();
    super.dispose();
  }

  // ─── KML generation ────────────────────────────────────────────────

  /// Builds a KML placemark with an HTML `<BalloonStyle>`.
  String _generateBalloonKml() {
    final title = _titleController.text.trim();
    final description = _descriptionController.text.trim();
    final imageUrl = _imageUrlController.text.trim();
    final lat = _latController.text.trim();
    final lng = _lngController.text.trim();

    final htmlContent = _buildBalloonHtml(
      title: title,
      description: description,
      imageUrl: imageUrl,
    );

    return '''<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>$title Balloon</name>
    <Style id="balloonStyle">
      <BalloonStyle>
        <text><![CDATA[$htmlContent]]></text>
        <bgColor>ffffffff</bgColor>
      </BalloonStyle>
    </Style>
    <Placemark>
      <name>$title</name>
      <styleUrl>#balloonStyle</styleUrl>
      <description><![CDATA[$htmlContent]]></description>
      <Point>
        <coordinates>$lng,$lat,0</coordinates>
      </Point>
    </Placemark>
  </Document>
</kml>''';
  }

  /// Produces clean HTML for the balloon popup.
  String _buildBalloonHtml({
    required String title,
    required String description,
    required String imageUrl,
  }) {
    return '''
<div style="font-family: Arial, sans-serif; width: 320px; padding: 8px;">
  <h2 style="margin: 0 0 8px 0; color: #1a73e8;">$title</h2>
  ${imageUrl.isNotEmpty ? '<img src="$imageUrl" style="width: 100%; border-radius: 8px; margin-bottom: 8px;" />' : ''}
  <p style="margin: 0; font-size: 14px; color: #333;">$description</p>
  <hr style="border: none; border-top: 1px solid #ddd; margin: 10px 0;" />
  <p style="margin: 0; font-size: 11px; color: #888;">Generated by LG Flutter Starter Kit</p>
</div>''';
  }

  // ─── Actions ───────────────────────────────────────────────────────

  /// Sends the generated balloon KML to the Liquid Galaxy rig.
  Future<void> _sendToLG() async {
    final lgService = context.read<LGService>();
    final kml = _generateBalloonKml();
    final lat = double.tryParse(_latController.text) ?? 0;
    final lng = double.tryParse(_lngController.text) ?? 0;

    setState(() {
      _isSending = true;
      _statusMessage = null;
    });

    try {
      final escaped = kml.replaceAll("'", "\\'");
      await lgService.executeRaw(
        "echo '$escaped' > /var/www/html/balloon.kml",
      );
      await lgService.executeRaw(
        'echo "http://localhost/balloon.kml" > /var/www/html/kmls.txt',
      );
      await lgService.flyTo(
        latitude: lat,
        longitude: lng,
        altitude: 500,
        range: 2000,
      );
      setState(() => _statusMessage = 'Balloon sent to LG ✓');
    } catch (e) {
      setState(() => _statusMessage = 'Error: $e');
    } finally {
      setState(() => _isSending = false);
    }
  }

  // ─── UI ────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(title: const Text('KML Balloon Demo')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // ── Input fields ───────────────────────────────────────
            Text('Balloon Content', style: theme.textTheme.titleMedium),
            const SizedBox(height: 12),
            TextFormField(
              controller: _titleController,
              decoration: const InputDecoration(
                labelText: 'Title',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.title),
              ),
              onChanged: (_) => setState(() {}),
            ),
            const SizedBox(height: 12),
            TextFormField(
              controller: _descriptionController,
              decoration: const InputDecoration(
                labelText: 'Description',
                alignLabelWithHint: true,
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.description),
              ),
              maxLines: 3,
              onChanged: (_) => setState(() {}),
            ),
            const SizedBox(height: 12),
            TextFormField(
              controller: _imageUrlController,
              decoration: const InputDecoration(
                labelText: 'Image URL',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.image),
              ),
              onChanged: (_) => setState(() {}),
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                Expanded(
                  child: TextFormField(
                    controller: _latController,
                    decoration: const InputDecoration(
                      labelText: 'Latitude',
                      border: OutlineInputBorder(),
                    ),
                    keyboardType: const TextInputType.numberWithOptions(
                      decimal: true,
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextFormField(
                    controller: _lngController,
                    decoration: const InputDecoration(
                      labelText: 'Longitude',
                      border: OutlineInputBorder(),
                    ),
                    keyboardType: const TextInputType.numberWithOptions(
                      decimal: true,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 20),

            // ── Send button ────────────────────────────────────────
            FilledButton.icon(
              onPressed: _isSending ? null : _sendToLG,
              icon: const Icon(Icons.send),
              label: const Text('Send to LG'),
            ),
            if (_isSending) ...[
              const SizedBox(height: 12),
              const LinearProgressIndicator(),
            ],
            if (_statusMessage != null) ...[
              const SizedBox(height: 12),
              Card(
                color: _statusMessage!.startsWith('Error')
                    ? theme.colorScheme.errorContainer
                    : theme.colorScheme.primaryContainer,
                child: Padding(
                  padding: const EdgeInsets.all(12),
                  child: Text(
                    _statusMessage!,
                    style: TextStyle(
                      color: _statusMessage!.startsWith('Error')
                          ? theme.colorScheme.onErrorContainer
                          : theme.colorScheme.onPrimaryContainer,
                    ),
                  ),
                ),
              ),
            ],
            const SizedBox(height: 24),

            // ── HTML preview ───────────────────────────────────────
            Text('Balloon HTML Preview', style: theme.textTheme.titleMedium),
            const SizedBox(height: 8),
            Card(
              color: theme.colorScheme.surfaceContainerHighest,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: SelectableText(
                  _buildBalloonHtml(
                    title: _titleController.text,
                    description: _descriptionController.text,
                    imageUrl: _imageUrlController.text,
                  ),
                  style: theme.textTheme.bodySmall?.copyWith(
                    fontFamily: 'monospace',
                    fontSize: 12,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 16),

            // ── Generated KML preview ──────────────────────────────
            Text('Generated KML', style: theme.textTheme.titleMedium),
            const SizedBox(height: 8),
            Card(
              color: theme.colorScheme.surfaceContainerHighest,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: SelectableText(
                  _generateBalloonKml(),
                  style: theme.textTheme.bodySmall?.copyWith(
                    fontFamily: 'monospace',
                    fontSize: 12,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
